### ISSUE TITLE
uninitialized constant PryStackExplorer::Pry when using Plymouth

### ISSUE THREAD

**Issue by jwhitley** [banister/plymouth#12]
When setting up Plymouth for a project (working on a repro via failing test on [mdub/clamp](https://github.com/mdub/clamp)), I'm seeing the following exception:

```
.../.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-stack_explorer-0.4.9/lib/pry-stack_explorer/commands.rb:133:in `<module:PryStackExplorer>': uninitialized constant PryStackExplorer::Pry (NameError)
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-stack_explorer-0.4.9/lib/pry-stack_explorer/commands.rb:1:in `<top (required)>'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-stack_explorer-0.4.9/lib/pry-stack_explorer.rb:5:in `require'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-stack_explorer-0.4.9/lib/pry-stack_explorer.rb:5:in `<top (required)>'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-exception_explorer-0.1.9/lib/pry-exception_explorer.rb:4:in `require'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/pry-exception_explorer-0.1.9/lib/pry-exception_explorer.rb:4:in `<top (required)>'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/plymouth-0.3.3/lib/plymouth.rb:4:in `require'
    from /Users/whitley/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/plymouth-0.3.3/lib/plymouth.rb:4:in `<top (required)>'
    from /Users/whitley/src/3p/clamp/spec/spec_helper.rb:4:in `require'
[...]
```

The root cause of the problem is that neither plymouth nor anything in its transitive dependency tree appears to `require 'pry'`.
### Repro notes

The exception above was produced with an RSpec run via `rake spec`, using bundler, on a locally modified mdub/clamp repo.  The local changes are unlikely to be relevant to this issue, as it bombs at load time before any changed code has been loaded.
### Workaround

In spec_helper.rb (or wherever plymouth is require'd):

```
require 'pry'
require 'plymouth'
```

**Comment by mpalmer** [comment]
Just wanted to +1 this bug; I'm getting exactly the same backtrace with a completely different project (a local webapp) and adding `require 'pry'` immediately before `require 'plymouth'` fixes the problem for me, too.

**Comment by ericridgeway** [comment]
+1 for the bug report, and +aMillion for the workaround

Thanks for the solution dude <3

**Comment by vighnesh1987** [comment]
You might need to add `gem 'pry'` before the `gem 'plymouth'` line in your Gemfile too. I got a similar error, but the backtrace was different. It occurred at the point in `application.rb` where it was trying to load the environment specific gems, one of which was pry.

```
/usr/local/rvm/gems/ruby-1.9.3-p194/gems/pry-stack_explorer-0.4.8/lib/pry-stack_explorer/commands.rb:133:in `<module:PryStackExplorer>': uninitialized constant PryStackExplorer::Pry (NameError)
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/pry-stack_explorer-0.4.8/lib/pry-stack_explorer/commands.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/pry-stack_explorer-0.4.8/lib/pry-stack_explorer.rb:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/pry-exception_explorer-0.1.9/lib/pry-exception_explorer.rb:4:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/plymouth-0.3.3/lib/plymouth.rb:4:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `block in require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
    from /Users/rege/LeanData/ld-server/config/application.rb:7:in `<top (required)>'
    from /Users/rege/LeanData/ld-server/config/environment.rb:2:in `require'
    from /Users/rege/LeanData/ld-server/config/environment.rb:2:in `<top (required)>'
    from /Users/rege/LeanData/ld-server/spec/spec_helper.rb:13:in `require'
    from /Users/rege/LeanData/ld-server/spec/spec_helper.rb:13:in `<top (required)>'
    from /Users/rege/LeanData/ld-server/spec/controllers/buckets_spec.rb:1:in `require'
    from /Users/rege/LeanData/ld-server/spec/controllers/buckets_spec.rb:1:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `block in load_spec_files'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load_spec_files'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:22:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
> /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/digest.rb:44:in `initialize': Operation not supported on socket - /Users/rege/LeanData/ld-server/.zeus.sock (Errno::EOPNOTSUPP)
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/digest.rb:44:in `open'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/digest.rb:44:in `file'
    from /usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/digest.rb:29:in `file'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:254:in `content_modified?'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:201:in `block in detect_modifications_and_removals'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:183:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:183:in `detect_modifications_and_removals'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:151:in `block in fetch_changes'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:149:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/directory_record.rb:149:in `fetch_changes'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/listener.rb:186:in `on_change'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/listener.rb:199:in `block in initialize_adapter'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/adapter.rb:196:in `call'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/adapter.rb:196:in `report_changes'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/adapter.rb:208:in `poll_changed_dirs'
    from /usr/local/rvm/gems/ruby-1.9.3-p194/gems/listen-0.5.1/lib/listen/adapters/darwin.rb:38:in `block in start'
```

**Comment by vighnesh1987** [comment]
The fix seems to be simple enough. I've sent out a pull-request.

p.s.: Love how easy it is to fork, edit and send a pull-request through the GitHub website!

**Comment by jwhitley** [comment]
@vighnesh1987 FWIW, plymouth should probably depend on `pry` in plymouth.gemspec, instead of relying on modifications to Gemfile.  That way any gem dependency will correctly pull in pry.  Likewise, it's arguably preferable to push the `pry` dependency into `pry-exception_explorer` (itself a dep in plymouth.gemspec) which also needs but doesn't correctly depend on `pry`.

**Comment by neohunter** [comment]
I require this to make it work:

require 'continuation' #without this i receive a undefined callcc method on Object
require 'pry' # without this uninitialized constant PryStackExplorer::Pry
require 'plymouth'

**Comment by HannesBenson** [comment]
Thanks @neohunter -  I also needed 'continuation' to get mine to work.

**Comment by xurde** [comment]
This is kinda weird.
I'm getting exactly this problem using plymouth (0.3.3) even when adding this to my `spec_helper`

```
require 'pry'
require 'pry-stack_explorer'
require 'plymouth'
```

Any clues?
