### ISSUE TITLE
Ruby2 Rails4rc1 backtrace in guard

### ISSUE THREAD

**Issue by kwerle** [banister/plymouth#14]
be guard...    

``` backtrace
10:59:52 - INFO - Running all specs
/Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/pry-exception_explorer-0.1.9/lib/pry-exception_explorer/core_ext.rb:91:in `raise': undefined method `callcc' for #<ActiveRecord::ConnectionAdapters::ConnectionSpecification::Resolver:0x007fb6aec29a18> (NoMethodError)
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/dependencies.rb:217:in `rescue in load_dependency'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/dependencies.rb:210:in `load_dependency'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/dependencies.rb:228:in `require'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/connection_adapters/connection_specification.rb:56:in `resolve_hash_connection'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/connection_adapters/connection_specification.rb:46:in `resolve_string_connection'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/connection_adapters/connection_specification.rb:30:in `spec'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/connection_handling.rb:39:in `establish_connection'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/railtie.rb:170:in `block (2 levels) in <class:Railtie>'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/lazy_load_hooks.rb:27:in `each'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.0.rc1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.0.rc1/lib/active_record/railtie.rb:168:in `block in <class:Railtie>'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/initializable.rb:30:in `run'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:180:in `each'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
  from /Users/kwerle/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/application.rb:214:in `initialize!'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.0.rc1/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from /Users/kwerle/Source/zepulator_v2/config/environment.rb:5:in `<top (required)>'
  from /Users/kwerle/Source/zepulator_v2/spec/spec_helper.rb:3:in `require'
  from /Users/kwerle/Source/zepulator_v2/spec/spec_helper.rb:3:in `<top (required)>'
  from /Users/kwerle/Source/zepulator_v2/spec/bulk_runner/bulk_runner_spec.rb:1:in `require'
  from /Users/kwerle/Source/zepulator_v2/spec/bulk_runner/bulk_runner_spec.rb:1:in `<top (required)>'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `block in load_spec_files'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `each'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load_spec_files'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:22:in `run'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
  from /Users/kwerle/.rvm/gems/ruby-2.0.0-p0/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by trystant** [comment]
I'm running into this issue as well; callcc needs to have the Continuation library required in 2.0. Add this to your "spec_helper.rb" and things should work:

require 'continuation'
